import SwiftUI

struct WhatsNewAenderung: Identifiable {
    let id = UUID()
    let icon: String
    let farbe: Color
    let titel: String
    let beschreibung: String
}

struct WhatsNewVersion {
    let version: String  // Anzeige in der UI, z.B. "2.0"
    let build: String    // Matching gegen CFBundleVersion, z.B. "5"
    let aenderungen: [WhatsNewAenderung]
}

/// Pflege hier vor jedem TestFlight-Upload die Neuerungen ein.
/// build muss exakt mit CFBundleVersion (Build-Nummer in Xcode) übereinstimmen.
let appChangelog: [WhatsNewVersion] = [
    WhatsNewVersion(version: "2.0", build: "27", aenderungen: [
        WhatsNewAenderung(icon: "rectangle.stack.fill", farbe: .indigo,
                          titel: "Wizard komplett neu gestaltet",
                          beschreibung: "Der Schmerz-Wizard ist jetzt ein moderner 5-Schritt-Karten-Wizard: Typ-Auswahl, 3D-Körperkarte, Intensität mit farbigem Zahlen-Kreis, Chip-Auswahl für Auslöser & Massnahmen und Wohlbefinden – alles im konsistenten Karten-Design."),
        WhatsNewAenderung(icon: "cube.transparent.fill", farbe: .teal,
                          titel: "3D-Körpermodell verbessert",
                          beschreibung: "Das 3D-Körpermodell lässt sich jetzt vertikal verschieben und füllt die gesamte Seite – mehr Fläche zum Antippen, weniger Scrollen. Datum und Wetter erscheinen direkt im ersten Schritt."),
        WhatsNewAenderung(icon: "wand.and.stars", farbe: .purple,
                          titel: "Alle 4 Module kombinierbar",
                          beschreibung: "Migräne, Schmerz, Rheuma und Diabetes lassen sich jetzt alle gleichzeitig auswählen – der sequenzielle Flow öffnet Formular für Formular in der gewählten Reihenfolge."),
        WhatsNewAenderung(icon: "tag.fill", farbe: .orange,
                          titel: "Eigene Auslöser & Massnahmen eintippen",
                          beschreibung: "Neben den vorgeschlagenen Chips können Auslöser und Massnahmen jetzt direkt als Freitext eingegeben werden – ohne Umweg über Notizen."),
        WhatsNewAenderung(icon: "brain.head.profile", farbe: .purple,
                          titel: "Migräne-Formular erweitert",
                          beschreibung: "Das Migräne-Formular hat einen eigenen Prodrom-Schritt, Multi-Select für die Lokalisation (einseitig links/rechts, beidseitig, Stirn etc.) und plant automatisch eine Push-Erinnerung für die Postdrom-Erfassung 24 Stunden nach dem Anfall."),
        WhatsNewAenderung(icon: "chart.bar.xaxis.ascending", farbe: .purple,
                          titel: "Migräne-Analyse",
                          beschreibung: "Neuer Analyse-Sheet direkt aus dem Migräne-Profil: 8 Sektionen mit Verlauf, Tageszeit-Muster, Auslöser, Aura & Dauer, Medikament-Wirksamkeit, Wetter- und Zyklus-Korrelation – inkl. Zeitraum-Filter (30T / 3M / 6M / 1J / Alle) und freier Anordnung per Drag & Drop."),
        WhatsNewAenderung(icon: "chart.xyaxis.line", farbe: .teal,
                          titel: "Verlauf-Chart scrollbar",
                          beschreibung: "Der Verlauf-Chart in der Migräne-Analyse ist horizontal scrollbar und startet automatisch beim aktuellen Monat. Bei langen Zeiträumen wird der X-Achsen-Abstand automatisch angepasst."),
        WhatsNewAenderung(icon: "info.circle.fill", farbe: .teal,
                          titel: "Infotexte bei jedem Chart",
                          beschreibung: "Jede Analyse-Sektion hat ein ⓘ-Symbol mit medizinischer Erklärung – was der Chart zeigt, wie er zu lesen ist und was die Werte bedeuten."),
        WhatsNewAenderung(icon: "arrow.clockwise.circle.fill", farbe: .teal,
                          titel: "Postdrom immer sichtbar",
                          beschreibung: "Postdromsymptome erscheinen in der Anfall-Detailansicht immer – mit Push-Erinnerungszeit falls noch nicht erfasst und einem «Jetzt erfassen»-Button. Tippen auf die Benachrichtigung öffnet direkt das fokussierte Erfassungs-Sheet."),
        WhatsNewAenderung(icon: "list.bullet.rectangle.fill", farbe: .purple,
                          titel: "Tagebuch: einheitliches Layout",
                          beschreibung: "Migräne-Einträge im Tagebuch zeigen jetzt dasselbe Layout wie Schmerzeinträge – SchmerzBadge, Überschrift mit Kopfschmerztyp, Charakter, Datum/Uhrzeit, Aura-Badge und Dauer auf einen Blick. Heutige Einträge zeigen die genaue Uhrzeit statt «vor X Minuten»."),
        WhatsNewAenderung(icon: "arrow.right.square.fill", farbe: .purple,
                          titel: "Migräne-Profil öffnet Detailansicht",
                          beschreibung: "Anfälle in der Migräne-Profil-Liste öffnen jetzt die vollständige Detailansicht statt direkt den Bearbeitungs-Wizard."),
    ]),
    WhatsNewVersion(version: "2.0", build: "26", aenderungen: [
        WhatsNewAenderung(icon: "switch.2", farbe: .teal,
                          titel: "Modulverwaltung im Profil",
                          beschreibung: "Im Profil gibt es jetzt den Abschnitt «Meine Module». Dort lassen sich Migräne, Rheuma & Gelenke und Diabetes ein- oder ausschalten. Aktivierte Module erscheinen beim Erfassen als Auswahlmöglichkeit."),
        WhatsNewAenderung(icon: "plus.square.fill.on.square.fill", farbe: .indigo,
                          titel: "Neuer Eintragsscreen",
                          beschreibung: "Beim Tippen auf + öffnet sich jetzt ein Auswahlscreen, sobald mindestens ein Modul aktiv ist. Schmerz, Migräne, Rheuma oder Diabetes – du wählst frei, was du erfassen möchtest. Mehrere Einträge gleichzeitig sind möglich."),
        WhatsNewAenderung(icon: "arrow.right.square.fill", farbe: .purple,
                          titel: "Kombinierter Migräne + Schmerz-Flow",
                          beschreibung: "Wenn du Migräne und Schmerz gleichzeitig auswählst, öffnet sich zuerst das Migräne-Formular und danach automatisch der Schmerzwizard – beide Einträge werden separat gespeichert."),
    ]),
    WhatsNewVersion(version: "2.0", build: "25", aenderungen: [
        WhatsNewAenderung(icon: "cloud.sun.fill", farbe: .cyan,
                          titel: "Migräne: Wetter-Autofill",
                          beschreibung: "Beim Öffnen eines neuen Migräne-Anfalls wird das aktuelle Wetter automatisch geladen und gespeichert – genau wie im Schmerzwizard. Temperatur, Wetterzustand und Wind erscheinen als kompakte Zeile im Formular."),
        WhatsNewAenderung(icon: "doc.richtext.fill", farbe: .purple,
                          titel: "Migräne-Seite im PDF-Export",
                          beschreibung: "Der PDF-Export enthält jetzt eine eigene Migräne-Seite: Statistik-Boxen (Anfälle, Ø Stärke, Aura, Ø Dauer), Top-5-Auslöser als Balkendiagramm, 8-Wochen-Verlauf und eine Detailtabelle mit farbkodierter Medikamenten-Wirksamkeit."),
        WhatsNewAenderung(icon: "bell.badge.fill", farbe: .orange,
                          titel: "Wirkungsabfrage nach Migräne",
                          beschreibung: "Nach dem Erfassen eines Anfalls mit Akutmedikament erscheint 90 Minuten später eine Benachrichtigung: «Wie hat [Medikament] gewirkt?» – damit kein Follow-up verloren geht."),
        WhatsNewAenderung(icon: "chart.line.uptrend.xyaxis", farbe: .indigo,
                          titel: "Migräne im Schmerzverlauf sichtbar",
                          beschreibung: "Migräne-Anfälle erscheinen jetzt als lila Rauten (◆) im Schmerzverlauf-Chart – auf derselben Skala wie Wizard-Einträge, aber klar unterschieden. Gibt es Migräne-Daten im Zeitraum, erscheint ein Hinweis in der Legende."),
        WhatsNewAenderung(icon: "staroflife.fill", farbe: .red,
                          titel: "Notfallausweis im Profil-Header",
                          beschreibung: "Der Notfallausweis ist jetzt direkt im Profil-Header sichtbar – Allergien und aktive Diagnosen als Chips auf einen Blick. Tippen öffnet den vollständigen Ausweis."),
        WhatsNewAenderung(icon: "list.clipboard.fill", farbe: .purple,
                          titel: "MIDAS-Fragebogen überarbeitet",
                          beschreibung: "Der MIDAS-Score-Bildschirm zeigt jetzt eine Score-Karte mit Verlaufschart und einen verbesserten Fragebogen im HAQ-Stil mit +/- Tages-Picker."),
        WhatsNewAenderung(icon: "plus.square.on.square", farbe: .teal,
                          titel: "Module im Dashboard hinzufügbar",
                          beschreibung: "Migräne-, Rheuma- und Diabetes-Kacheln können jetzt über «Dashboard anpassen» gezielt hinzugefügt werden – auch wenn sie nicht in der Standard-Ansicht erscheinen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "24", aenderungen: [
        WhatsNewAenderung(icon: "brain.head.profile", farbe: .purple,
                          titel: "Migräne-Modul",
                          beschreibung: "Anfall-Tagebuch mit Auslöser-Analyse, Aura, Begleitsymptome und Akutmedikament. Dashboard-Kachel mit 14-Tage-Diagramm. Schmerzwizard erkennt Migräne automatisch und bietet Direktübernahme an."),
        WhatsNewAenderung(icon: "drop.fill", farbe: .orange,
                          titel: "Diabetes-Modul",
                          beschreibung: "Blutzucker-Tagebuch mit mmol/L-Erfassung, Messzeitpunkte (Nüchtern, vor/nach Essen), Insulin-Tracking und Zielbereich-Statistik."),
        WhatsNewAenderung(icon: "list.bullet.rectangle.portrait.fill", farbe: .blue,
                          titel: "Profil neu strukturiert",
                          beschreibung: "Drei klare Sektionen: Gesundheit (inkl. Arztbesuche, Laborwerte, Physiotherapie), Erkrankungen (Rheuma, Migräne, Diabetes) und Notfall & Kontakte. Rheuma zeigt nur noch krankheitsspezifische Inhalte."),
    ]),
    WhatsNewVersion(version: "2.0", build: "22", aenderungen: [
        WhatsNewAenderung(icon: "doc.richtext.fill", farbe: .purple,
                          titel: "Rheuma-Seite im PDF",
                          beschreibung: "Der PDF-Export enthält jetzt eine eigene Rheuma-Seite mit HAQ-DI-Verlauf, Laborwerte-Tabelle, Schub-Statistik und Auslöser-Vergleich (Schub vs. kein Schub). Einzelne Einträge zeigen auch betroffene Gelenke (TJC/SJC)."),
        WhatsNewAenderung(icon: "flame.fill", farbe: .red,
                          titel: "Schübe / Flares in der Zusammenfassung",
                          beschreibung: "Die Zusammenfassung im PDF zeigt jetzt 5 Stat-Boxen: Ø Schmerzstärke, Höchstwert, Tage mit Schmerz, Schübe / Flares und MIDAS-Score – auf einen Blick."),
        WhatsNewAenderung(icon: "testtube.2", farbe: .blue,
                          titel: "Biologika, Kortison & Physiotherapie",
                          beschreibung: "Neue Tracker für Biologika-Injektionen (mit Chargen-Nr. und nächster Dosis), Kortison-Tagebuch mit Dosierungsverlauf und Physiotherapie-Protokoll – alle im Rheuma-Modul."),
        WhatsNewAenderung(icon: "checkmark.seal.fill", farbe: .green,
                          titel: "Remissionsphasen & FACIT",
                          beschreibung: "Remissionsphasen lassen sich mit Start und Ende dokumentieren – ein Live-Timer zeigt die bisherige Dauer. Der FACIT-Erschöpfungsfragebogen (13 Fragen) misst Fatigue auf einer 52-Punkte-Skala."),
        WhatsNewAenderung(icon: "staroflife.fill", farbe: .orange,
                          titel: "Notfallausweis & Diagnosen",
                          beschreibung: "Ein digitaler Notfallausweis fasst alle wichtigen Daten zusammen – Diagnosen, Immunsuppressiva-Warnung, Notfallkontakte. Die Diagnose-Verwaltung listet aktive und frühere Diagnosen mit ICD-Code."),
    ]),
    WhatsNewVersion(version: "2.0", build: "21", aenderungen: [
        WhatsNewAenderung(icon: "figure.arms.open", farbe: .purple,
                          titel: "Rheuma & Gelenke Modul",
                          beschreibung: "Das vollständige Rheuma-Modul ist jetzt unter Profil → Rheuma & Gelenke erreichbar: HAQ-Fragebogen mit DAS28-Score, Gelenkstatus mit 39 Gelenken, Laborwerte mit Verlaufskurven, Arztbesuche, Impfpass und Arztbrief-Vorlage. Schübe (Flare) und Fatigue lassen sich direkt beim Eintrag erfassen."),
        WhatsNewAenderung(icon: "hand.point.up.left.fill", farbe: .purple,
                          titel: "Gelenke optional erfassen",
                          beschreibung: "Der Gelenkstatus kann jetzt optional im Wizard aktiviert werden – genau wie der Schub-Modus. Ein Haken reicht, und der Wizard fügt automatisch den Gelenkstatus-Schritt ein. Ohne Haken bleibt der Ablauf unverändert kurz."),
        WhatsNewAenderung(icon: "syringe.fill", farbe: .teal,
                          titel: "Impfpass im Profil",
                          beschreibung: "Der Impfpass ist jetzt unter Profil → Gesundheit zu finden – neben Medikamenten, Rheuma & Gelenke und MIDAS. Einträge lassen sich jetzt per Wischen bearbeiten und löschen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "20", aenderungen: [
        WhatsNewAenderung(icon: "figure.arms.open", farbe: .purple,
                          titel: "Rheuma & Gelenke",
                          beschreibung: "Neues Modul für Rheuma- und Chronikpatienten: HAQ-Fragebogen mit DAS28-Score, Gelenkstatus-Erfassung, Laborwerte mit Verlaufskurven, Arztbesuche, Impfpass und Arztbrief-Vorlage – alles unter Profil → Rheuma & Gelenke."),
        WhatsNewAenderung(icon: "flame.fill", farbe: .red,
                          titel: "Schub-Modus & Fatigue",
                          beschreibung: "Beim Erfassen eines Eintrags kann ein Rheuma-Schub (Flare) markiert und die Erschöpfung (Fatigue 0–10) erfasst werden. Schübe erscheinen mit Flammen-Badge in der Tagebuchliste und werden im Analysen-Tab ausgewertet."),
        WhatsNewAenderung(icon: "hand.point.up.left.fill", farbe: .blue,
                          titel: "Gelenkdiagramm",
                          beschreibung: "Im Erfassungs-Wizard gibt es einen neuen Schritt für den Gelenkstatus: 39 Gelenke können als schmerzhaft, geschwollen oder beides markiert werden. DAS28-relevante Gelenke werden automatisch erkannt."),
        WhatsNewAenderung(icon: "doc.text.fill", farbe: .teal,
                          titel: "Arztbrief-Vorlage",
                          beschreibung: "Erzeuge mit einem Tap einen strukturierten Arztbrief mit Schmerzstatistik, Medikamenten, Laborwerten und Arztbesuchen – direkt teilen oder in die Zwischenablage kopieren."),
    ]),
    WhatsNewVersion(version: "2.0", build: "19", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill", farbe: .indigo,
                          titel: "Benachrichtigungen zentral verwalten",
                          beschreibung: "Alle Erinnerungen an einem Ort: Tägliche Erinnerung, Wasser-Erinnerung und Medikamenten-Zeiten lassen sich direkt über Einstellungen → Benachrichtigungen konfigurieren."),
        WhatsNewAenderung(icon: "magnifyingglass", farbe: .blue,
                          titel: "Kontaktsuche im Adressbuch",
                          beschreibung: "Die Kontaktauswahl für Arzt und Notfallkontakte zeigt jetzt eine Suchleiste – du findest Kontakte sofort durch Tippen."),
        WhatsNewAenderung(icon: "sunrise.fill", farbe: .orange,
                          titel: "Morgensteifigkeit vollständig dokumentiert",
                          beschreibung: "Morgensteifigkeit erscheint jetzt in der Tagebuchliste, im Detaileintrag, in der Analyse (Körper & Geist) und im PDF-Export."),
        WhatsNewAenderung(icon: "arrow.trianglehead.branch", farbe: .teal,
                          titel: "Alle Push-Deep-Links aktiv",
                          beschreibung: "Tippen auf eine Benachrichtigung öffnet jetzt immer die richtige Ansicht – auch für Vorrat, Ablauf, Wasser und Zyklus."),
    ]),
    WhatsNewVersion(version: "2.0", build: "18", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill", farbe: .indigo,
                          titel: "Benachrichtigungen zentral verwalten",
                          beschreibung: "Alle Erinnerungen an einem Ort: Tägliche Erinnerung, Wasser-Erinnerung und Medikamenten-Zeiten lassen sich jetzt direkt über Einstellungen → Benachrichtigungen konfigurieren."),
        WhatsNewAenderung(icon: "magnifyingglass", farbe: .blue,
                          titel: "Kontaktsuche im Adressbuch",
                          beschreibung: "Die Kontaktauswahl für Arzt und Notfallkontakte zeigt jetzt eine Suchleiste – du findest Kontakte sofort durch Tippen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "17", aenderungen: [
        WhatsNewAenderung(icon: "magnifyingglass.circle.fill", farbe: .blue,
                          titel: "Erweiterte Arztsuche",
                          beschreibung: "Die Arztsuche kombiniert jetzt Apple Maps und OpenStreetMap: drei parallele Suchanfragen laufen gleichzeitig, erste Ergebnisse erscheinen sofort – weitere kommen lautlos nach."),
        WhatsNewAenderung(icon: "bolt.fill",                   farbe: .yellow,
                          titel: "Arztsuche deutlich schneller",
                          beschreibung: "Ergebnisse werden jetzt schrittweise geladen statt erst nach Abschluss aller Quellen – die Liste erscheint bereits nach etwa einer Sekunde."),
    ]),
    WhatsNewVersion(version: "2.0", build: "16", aenderungen: [
        WhatsNewAenderung(icon: "person.crop.circle.badge.plus", farbe: .blue,
                          titel: "Arzt-Import verbessert",
                          beschreibung: "Beim Import aus dem Adressbuch werden jetzt Praxisname, Arztname, Adresse, Telefon und E-Mail korrekt auf separate Felder verteilt – auch bei Praxis-Kontakten ohne persönlichen Namen."),
        WhatsNewAenderung(icon: "building.2",                   farbe: .teal,
                          titel: "Arzt-Felder neu strukturiert",
                          beschreibung: "Das Arzt-Formular hat jetzt separate Felder für Praxis/Klinik, Name des Arztes, Fachgebiet und Adresse – übersichtlicher und vollständiger."),
    ]),
    WhatsNewVersion(version: "2.0", build: "15", aenderungen: [
        WhatsNewAenderung(icon: "sunrise",                   farbe: .orange,
                          titel: "Morgensteifigkeit erfassen",
                          beschreibung: "Im Wohlbefinden-Schritt kannst du jetzt angeben, wie lange die Morgensteifigkeit nach dem Aufstehen angehalten hat – ein wichtiger Wert für Rücken- und Rheuma-Patienten."),
        WhatsNewAenderung(icon: "drop.halffull",             farbe: .pink,
                          titel: "Periode: Nur halber Tag",
                          beschreibung: "Im Zyklus-Eintrag gibt es jetzt den Toggle 'Nur halber Tag', wenn eine Blutung erfasst wird – z.B. für Tage mit kurzem Einsetzen oder Ende der Periode."),
        WhatsNewAenderung(icon: "person.crop.circle.badge.plus", farbe: .blue,
                          titel: "Arzt aus Adressbuch",
                          beschreibung: "Ärzte können jetzt direkt aus dem iOS-Adressbuch importiert werden – Name, Telefon und E-Mail werden automatisch übernommen."),
        WhatsNewAenderung(icon: "clock.arrow.trianglehead.counterclockwise.rotate.90", farbe: .indigo,
                          titel: "Versionsverlauf",
                          beschreibung: "Unter Einstellungen → App findest du jetzt den vollständigen Versionsverlauf aller bisherigen Updates."),
    ]),
    WhatsNewVersion(version: "2.0", build: "14", aenderungen: [
        WhatsNewAenderung(icon: "bolt.fill", farbe: .yellow,
                          titel: "Schnellerer App-Start",
                          beschreibung: "Der Benachrichtigungs-Status wird jetzt im Hintergrund geladen – der App-Start ist dadurch spürbar flüssiger."),
    ]),
    WhatsNewVersion(version: "2.0", build: "13", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill",           farbe: .blue,
                          titel: "Benachrichtigungen beim Kaltstart",
                          beschreibung: "Deep Links aus Benachrichtigungen funktionieren jetzt auch zuverlässig, wenn die App vollständig geschlossen war – die richtige Ansicht öffnet sich direkt nach dem Tippen auf eine Mitteilung."),
        WhatsNewAenderung(icon: "calendar.badge.plus",       farbe: .green,
                          titel: "Monatliche Frequenz",
                          beschreibung: "Medikamente können jetzt als 'Monatlich' eingestellt werden. Die Erinnerung erscheint jeden Monat am gleichen Tag wie das Startdatum."),
        WhatsNewAenderung(icon: "slider.horizontal.3",       farbe: .teal,
                          titel: "Zeitfilter oben",
                          beschreibung: "Der Zeitfilter im Analysen-Tab steht jetzt an erster Stelle – noch vor der Zusammenfassung, sodass die Filterauswahl sofort sichtbar ist."),
    ]),
    WhatsNewVersion(version: "2.0", build: "12", aenderungen: [
        WhatsNewAenderung(icon: "chart.bar.doc.horizontal.fill", farbe: .indigo,
                          titel: "Analysen komplett neu strukturiert",
                          beschreibung: "Der Analysen-Tab ist jetzt in drei Bereiche aufgeteilt: 'Überblick' mit Erkenntnissen, Vorhersage und Verlauf – 'Muster' mit allen Korrelations-Charts – 'Medikamente' mit Adherenz, Wirksamkeit und Injektionszyklus."),
        WhatsNewAenderung(icon: "slider.horizontal.3",           farbe: .teal,
                          titel: "Zeitfilter für Analysen",
                          beschreibung: "Über den Filter 30 T / 90 T / Alle lassen sich alle Muster-Charts gleichzeitig auf einen bestimmten Zeitraum einschränken."),
        WhatsNewAenderung(icon: "sparkle.magnifyingglass",       farbe: .orange,
                          titel: "Erkenntnisse neu gestaltet",
                          beschreibung: "Die Erkenntnisse-Karte hat ein frisches Design erhalten: farbige Icon-Quadrate statt gelbem Hintergrund – konsistent mit dem Rest der App."),
        WhatsNewAenderung(icon: "eye.slash",                     farbe: .secondary,
                          titel: "Leere Charts ausgeblendet",
                          beschreibung: "Sektionen und Charts ohne ausreichend Daten werden nicht mehr angezeigt – die Ansicht bleibt übersichtlich und zeigt nur relevante Informationen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "11", aenderungen: [
        WhatsNewAenderung(icon: "calendar.badge.clock",       farbe: .indigo,
                          titel: "Schmerzkalender",
                          beschreibung: "Neue Heatmap-Ansicht der letzten 6 Monate: Jeder Tag ist nach Schmerzstärke eingefärbt. Antippen öffnet alle Einträge des Tages direkt."),
        WhatsNewAenderung(icon: "wand.and.stars",             farbe: .purple,
                          titel: "7-Tage-Vorhersage",
                          beschreibung: "Prognostizierter Schmerzwert für die nächsten 7 Tage – basierend auf deinen Wochentagsmustern und dem aktuellen Trend. Zeigt deinen besten und schwierigsten Tag der Woche."),
        WhatsNewAenderung(icon: "arrow.up.right.circle.fill", farbe: .teal,
                          titel: "Tages-Drill-down",
                          beschreibung: "Aus dem Schmerzverlauf-Chart und der Heatmap kannst du direkt in einen Tag einsteigen und alle Einträge mit Schmerz, Ort, Auslöser und Notizen sehen."),
        WhatsNewAenderung(icon: "moon.zzz.fill",              farbe: .orange,
                          titel: "Fokus-Modus & Nicht stören",
                          beschreibung: "Erinnerungen kommen jetzt auch durch, wenn der Fokus-Modus oder 'Nicht stören' aktiv ist – sofern 'Zeitkritische Mitteilungen' in den iOS-Einstellungen erlaubt ist. Ein Hinweis in den App-Einstellungen führt dich direkt dorthin."),
        WhatsNewAenderung(icon: "checkmark.circle.fill",      farbe: .green,
                          titel: "Zyklus-Eintrag korrigiert",
                          beschreibung: "Beim Bearbeiten eines bestehenden Zyklus-Eintrags wurde die sexuelle Aktivität nicht korrekt angezeigt. Das ist jetzt behoben."),
        WhatsNewAenderung(icon: "sparkles",                   farbe: .blue,
                          titel: "Was ist neu jederzeit abrufbar",
                          beschreibung: "Unter Einstellungen → App gibt es jetzt einen 'Was ist neu'-Button, der den Changelog jederzeit öffnet."),
    ]),
    WhatsNewVersion(version: "2.0", build: "10", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill",          farbe: .blue,
                          titel: "Erinnerungen nach Update zuverlässig",
                          beschreibung: "Nach einer Neuinstallation oder einem App-Update werden alle Medikamenten-Erinnerungen, Tages- und Wasser-Erinnerungen automatisch neu geplant."),
        WhatsNewAenderung(icon: "bell.and.waves.left.and.right", farbe: .indigo,
                          titel: "Benachrichtigung testen",
                          beschreibung: "In den Einstellungen unter 'Erinnerungen' gibt es jetzt einen Test-Button – Push kommt nach 5 Sekunden, funktioniert auch wenn die App geöffnet ist."),
        WhatsNewAenderung(icon: "arrow.up.arrow.down",      farbe: .green,
                          titel: "Wochentend sensibler",
                          beschreibung: "Der Trend-Badge zeigt bereits ab einer Veränderung von ±0.05 Farbe – kleine Verbesserungen oder Verschlechterungen werden jetzt sichtbar."),
    ]),
    WhatsNewVersion(version: "2.0", build: "9", aenderungen: [
        WhatsNewAenderung(icon: "calendar.badge.checkmark", farbe: .blue,
                          titel: "Wochenvergleich Mo–So",
                          beschreibung: "Der Trend-Badge und 'Diese Woche' basieren jetzt auf echten Kalenderwochen (Montag bis Sonntag) statt einem rollenden 7-Tage-Fenster."),
        WhatsNewAenderung(icon: "pill.fill",               farbe: .green,
                          titel: "Bewertungs-Push öffnet Medikamente",
                          beschreibung: "Tippe auf 'Hat X gewirkt?' – die Medikamenten-Ansicht öffnet sich direkt mit der Bewertungssektion."),
        WhatsNewAenderung(icon: "wrench.and.screwdriver.fill", farbe: .orange,
                          titel: "Kleinere Bugfixes",
                          beschreibung: "Wöchentliche Injektionen werden korrekt nach Dosierung gefiltert. Ablaufdatum-Anzeige und Einnahme-Zählung im Dashboard präzisiert."),
    ]),
    WhatsNewVersion(version: "2.0", build: "8", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill",        farbe: .blue,
                          titel: "Push-Links immer zuverlässig",
                          beschreibung: "Deep Links funktionieren jetzt in allen Situationen: App geschlossen, im Hintergrund oder aktiv. Wirksamkeits-Abfrage öffnet direkt die Medikamenten-Karte."),
        WhatsNewAenderung(icon: "icloud.fill",            farbe: .cyan,
                          titel: "iCloud-Sync stabiler",
                          beschreibung: "UIBackgroundModes ist jetzt explizit in der Info.plist gesetzt – CloudKit kann Push-Benachrichtigungen für die Synchronisation zuverlässig empfangen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "7", aenderungen: [
        WhatsNewAenderung(icon: "bell.badge.fill",        farbe: .blue,
                          titel: "Smarte Benachrichtigungen",
                          beschreibung: "Tippe auf eine Medikamenten-Erinnerung und die Einnahme-Maske öffnet sich direkt. Schmerz-Erinnerung öffnet die Erfassung."),
        WhatsNewAenderung(icon: "tag.fill",               farbe: .purple,
                          titel: "Eigene Chips werden gemerkt",
                          beschreibung: "Selbst eingegebene Auslöser, Schmerzarten, Begleiterscheinungen und Massnahmen erscheinen beim nächsten Eintrag direkt als Vorschlag."),
        WhatsNewAenderung(icon: "moon.zzz.fill",           farbe: .indigo,
                          titel: "Schlafstunden übernommen",
                          beschreibung: "Beim zweiten Eintrag des Tages werden die Schlafstunden vom ersten Eintrag automatisch vorausgefüllt."),
        WhatsNewAenderung(icon: "figure.walk",            farbe: .orange,
                          titel: "Onboarding verbessert",
                          beschreibung: "Das Textfeld beim Namen-Schritt war hinter der Tastatur versteckt – jetzt scrollt die Ansicht korrekt."),
    ]),
    WhatsNewVersion(version: "2.0", build: "6", aenderungen: [
        WhatsNewAenderung(icon: "doc.richtext.fill",  farbe: .blue,
                          titel: "Arztbesuch-PDF verbessert",
                          beschreibung: "Vollständiges Einnahme-Protokoll mit allen Logs, unbegrenzt viele Seiten."),
        WhatsNewAenderung(icon: "moon.fill",          farbe: .indigo,
                          titel: "Dark Mode",
                          beschreibung: "PDF-Vorschau funktioniert jetzt korrekt im Dark Mode."),
        WhatsNewAenderung(icon: "bolt.fill",          farbe: .orange,
                          titel: "Schnellere PDF-Erstellung",
                          beschreibung: "PDF wird im Hintergrund erstellt – die App bleibt flüssig."),
        WhatsNewAenderung(icon: "person.fill.viewfinder", farbe: .teal,
                          titel: "Profil-Header überarbeitet",
                          beschreibung: "iOS-Settings-Stil mit Foto, Badges und direktem Bearbeiten."),
        WhatsNewAenderung(icon: "lock.fill",          farbe: .green,
                          titel: "Biometrische Sperre",
                          beschreibung: "Face ID / Touch ID jetzt in den App-Einstellungen."),
    ]),
    WhatsNewVersion(version: "2.0", build: "5", aenderungen: [
        WhatsNewAenderung(icon: "doc.richtext.fill",  farbe: .blue,
                          titel: "Arztbesuch-PDF verbessert",
                          beschreibung: "Vollständiges Einnahme-Protokoll mit allen Logs, unbegrenzt viele Seiten."),
        WhatsNewAenderung(icon: "moon.fill",          farbe: .indigo,
                          titel: "Dark Mode",
                          beschreibung: "PDF-Vorschau funktioniert jetzt korrekt im Dark Mode."),
        WhatsNewAenderung(icon: "bolt.fill",          farbe: .orange,
                          titel: "Schnellere PDF-Erstellung",
                          beschreibung: "PDF wird im Hintergrund erstellt – die App bleibt flüssig."),
        WhatsNewAenderung(icon: "person.fill.viewfinder", farbe: .teal,
                          titel: "Profil-Header überarbeitet",
                          beschreibung: "iOS-Settings-Stil mit Foto, Badges und direktem Bearbeiten."),
        WhatsNewAenderung(icon: "lock.fill",          farbe: .green,
                          titel: "Biometrische Sperre",
                          beschreibung: "Face ID / Touch ID jetzt in den App-Einstellungen."),
    ]),
]

/// Gibt den Changelog-Eintrag für den aktuell installierten Build zurück.
func whatsNewFuerAktuelleVersion() -> WhatsNewVersion? {
    let build = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String ?? ""
    return appChangelog.first { $0.build == build }
}
